name: Rust

on: [workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    #- name: Install rustup i686-pc-windows-msvc target
    #  run: rustup target add i686-pc-windows-msvc
    - name: Build
      run: cargo build --verbose --release --target=i686-pc-windows-msvc
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: d3d9.dll
        path: target/i686-pc-windows-msvc/release/d3d9.dll
